name: Build APK with Docker
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Docker Latest
        run: |
          # سحب الصورة الصحيحة اللي قلت لي عليها
          docker pull ghcr.io/kivy/buildozer:latest
          
          # تشغيل البناء مع ربط المجلدات الصواب
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/hostproxy \
            -v ${{ github.workspace }}/.buildozer:/home/user/.buildozer \
            ghcr.io/kivy/buildozer:latest \
            android debug
